platform :ios, '10.0'
inhibit_all_warnings!

use_frameworks!
target 'CircuitSDK_Tests' do
  pod 'CircuitSDK', :path => '../'
end

target 'SampleApp' do
  pod 'CircuitSDK', :path => '../'
  pod 'AppAuth'
  pod 'Kingfisher', '~> 3.0.0'
end
