language: objective-c
podfile: Example/Podfile
osx_image: xcode9.2

before_install:
- gem install activesupport -v 4.2.6 # Need this because of travis
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -workspace Example/CircuitSDK.xcworkspace -scheme CircuitSDK-Example -destination 'platform=iOS Simulator,name=iPhone 6' | xcpretty

