whitelist_rules:
 - legacy_cggeometry_functions
 - unused_optional_binding
 - empty_parentheses_with_trailing_closure
 - trailing_semicolon
 - implicit_getter
 - empty_parameters
 - opening_brace
 - valid_ibinspectable
 - closure_parameter_position
 - colon
 - return_arrow_whitespace
 - mark
 - redundant_void_return
 - generic_type_name
 - trailing_comma
 - closing_brace
 - trailing_newline
 - syntactic_sugar
 - vertical_whitespace
 - weak_delegate
 - dynamic_inline
 - legacy_nsgeometry_functions
 - operator_whitespace
 - void_return
 - leading_whitespace
 - legacy_constructor
 - todo
 - function_parameter_count
 - redundant_string_enum_value
 - class_delegate_protocol
 - vertical_parameter_alignment
 - custom_rules
 - private_unit_test
 - trailing_whitespace
 - compiler_protocol_init
 - comma
 - redundant_optional_initialization
 - unused_enumerated
 - legacy_constant
 - nesting
 - statement_position
 - control_statement
excluded:
 - Pods
